trigger:
- main

pool:
    name: Default

variables:
    buildConfiguration: 'Release'

steps:
- script: dotnet buld --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'